sudo: required
services:
        - docker 

before_install:
        - docker build -t vinaym/docker-react -f Dockerfile.dev .

script:
        - docker run vinaym/docker-react npm run test -- --coverage

deploy:
        provider: elasticbeanstalk
        region: "ap-south-1"
        app: "Docker"
        env: "Docker-env" 
        bucket_name: "elasticbeanstalk-ap-south-1-050959244039"
        bucket_path: "Docker"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"

